import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="flex p-2 bg-indigo-500">
            <h2 className="text-2xl">Ultimate Pokedex</h2>
              <a href="/">Home</a>
              <a href="/pokemon">Pokemon</a>
              <a href="/location">Locations</a>
              <a href="/move">Moves</a>
              <a href="/generation">Generations</a>
            </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}